language: go
script:
- env
- go version
- echo $MY_SECRET_ENV
env:
  global:
    secure: mhXYExP1wczfuLyCRI/vkhvZGOb8uiqG929VxOXozemHG3YboePvr/amQBc8Br7FRX4VhiEBl9XoOnJr2WAOQjpG6OtWSzfSdj6E/v/hPdnLB8Z9fCBqnMSabYLDtNjdM5uHNGoEwz14+JFbu65UUuLZHX+gGL6zibfhl7FhdoTWVLzA9XFqYsFSP4eCjWcyVNTYBNkSRBFB7srAIi3GdFd4nqHaca15OkwklvggxOp3+PYghXmP1zTvDa81W0WBvIEETapvbI9NNf4paMMrUJnuQZvwb0Mb0Zjo0Nx7hBUC/ODexAuwOX+vZD0KbWID5iFoV89lFff85Gi3h2WhAQqUp8s2l8zWGI0Jg1rOTcdiPNOzFUymlMIrevWr5xFguDjwKjZMN65i2B6RXDKHivix0QL80nCoSGzyXowiaMl1+G3kgpV91r0UpQPT4QBv3GXDrsi4RQRvLwy9zY/VS9JJBq9GjKEN9P2s+mBSCZabHznx3f0fTS+6LL7bl1Lw4GEJKGEVc3Bt3Em2fkpl4HSJvPcFTt9sNlmp39wWyiA003LXiWIbbCBbFVqaY6RJbPSk6D+JGXAxg/fQY5qt9mKKg2ua1i7b55kflE2umnuyQDSZV2vR7BvTs91woZBZN5qnYLXw2BNaFJ4tvfPVtxgYj3ahIWPT3VfJMpU3zsc=
